### ISSUE TITLE
Data Source Nzy3d

### ISSUE THREAD

**Issue by azsh07** [benoit74/nzy3d-api#2]
Hi benoit74,

I already try the winforms demo and its success. However, I cant figure out how to link my data source into this chart.

Can you guide me how to link it?

Many thanks

**Comment by benoit74** [comment]
Hi,

The class responsible for giving the data to the library is the MyMapper.cs
in the samples. A Mapper inherits the nzy3D.Plot3D.Builder.Mapper
interface. It implements a single function
"public override double f(double x, double y)" which computes the z-value
for a given x-value y-value couple.

The solution hence consists in implementing your own mapper class and link
it in the Form1.cs.

Shape surface = Builder.buildOrthonomal(new OrthonormalGrid(range, steps,
range, steps), new MyMapper());

Of course if you don't have a function but a dataset of x/y/z, you should
use interpolation/extrapolation in the Mapper class.

Cheers,

Benoît

2015-04-16 16:39 GMT+02:00 azsh07 <notifications@github.com>:

**Comment by azsh07** [comment]
Thanks Benoit for your reply. I found it is quite difficult to understand since I am beginner. 

What I am trying to do is to make the chart bind to the datagridview in winforms where x (column 1), y (column 2) and z (column 3). I am looking your code and find the interpolation inside the mapper class are difficult to understand. However I trying my hard to find the solution for this question since your chart proved are suitable for my project.

If you have any advice, I am very grateful. Thanks for your time for such noob as me.

**Comment by gonzalezk** [comment]
Hi benoit74,
Is it possible to build a 3D scatter plot with your nzy3D toolkit.

This kit is real nice.
