### ISSUE TITLE
Rescaling the z-axis

### ISSUE THREAD

**Issue by Bovaz** [benoit74/nzy3d-api#3]
Hello,

Congratulations for this library. I am finding it very useful.
However I seem to be unable to rescale properly the z-axis. For my application I want to plot very low values, that may vary by quite a lot (2-3 orders of magnitude), on a rectangular "base" (meaning that x and y axis have different length).
I have set the chart.View.Squared property to false to accomodate the dimensions of x and y axis, and changed the point of view to have the correct "perspective". However I am unable to properly show the third dimension for the z-axis, because the values are very low.

The range may be 150 (for x-axis) by 70 (for y-axis) by 1e-7 (for z-axis). The z-values are basically drawn flat. See the attached picture. The color scale gives you an idea of the profile I would like.
![flatzaxis](https://cloud.githubusercontent.com/assets/11745229/7439518/1dfb2940-f033-11e4-93b9-051182b45c4c.png)

Thank you for any help you may be able to provide.

**Comment by benoit74** [comment]
Hello,

Thank you very much for your interest in nzy3d.

From what I've seen in my tests and in the code, the "Squared" option is
working in the oposite way of what you think (i.e. you should set Squarred
to true when you don't want it to be Squared ...). See below a slightly
modify sample where the axes have the same ranges you spoke about.

Cheers,

Benoît

[image: Images intégrées 1]


2015-05-02 3:52 GMT+02:00 Bovaz <notifications@github.com>:

**Comment by Bovaz** [comment]
Hello,

Sorry if I am only getting back now.

I cannot see the image you attached.

From my tests, if I set Squared to true, the chart it's actually contained in a cube.
If I don't, I am able to get the image I attached earlier. It feels to me that the issue with my visualization is that the values on the z-axis are few orders of magnitude smaller than the coordinates.
