### ISSUE TITLE
Memory leaks?

### ISSUE THREAD

**Issue by Bovaz** [benoit74/nzy3d-api#4]
I have been using the library to display some data. I am talking about quite long data series. The way I am doing it is by scrolling through each "frame" of data, and displaying it, one at a time. After a while, upon changing to the next frame, I get "Out of Memory" exceptions from functions in the library. For example, the latest was in a constructor for a Point object.

I have not been able to point out exactly what is raising the issue, and I will post back here if I can find it precisely, but I was wondering if you had seen this already.

Thank you.

**Comment by benoit74** [comment]
Not enough information so far and not reproduced in our tests.
