### ISSUE TITLE
ColorMapper

### ISSUE THREAD

**Issue by RainerAtGitHub** [benoit74/nzy3d-api#7]
Dear benoid74,

thank you very much for sharing your fantastic api. It's a big step forward in my small project just by copy and paste. I was able to enter my array of data by overwrite f(x,y).  The data appears just like a mountain and is better understandable. 

The rainbow painting is very nice, but for a more scientific use I would prefer to use flat colors for a meaningful  z-value-range. So the mountain should be build up as a stack of colored slices. Then it would be possible to identify the z-values in every perspective. 

The api has already an automatic scaling, working as perfect for zmax = 500 as for zmax = 10000. So how can I change the ColorMapper to create 5 slices for the first sample and 10 slices for the second?

Rainer

**Comment by benoit74** [comment]
Hi Rainer,

In the example provided below, you will see that you can provide your own ColorMap:
https://github.com/benoit74/nzy3d-api/blob/dc406bf8791eb1e07a1bfe9ff1d96743efbafd93/nzy3d-wpfDemo/MainWindow.xaml.cs#L78

In your case, you should probably implement your own ColorMap class, which must inherit from IColorMap:
https://github.com/benoit74/nzy3d-api/blob/dc406bf8791eb1e07a1bfe9ff1d96743efbafd93/nzy3d-api/Colors/ColorsMaps/IColorMap.cs
With this, you can decide which color to apply for given, x, y, z values. So you could do whatever you could imagine.

Regards,

Benoît

**Comment by jzy3d** [comment]
Hi,

The Colormap javadoc may be helpfull

http://doc.jzy3d.org/javadoc/1.0.0/jzy3d-api/org/jzy3d/colors/colormaps/IColorMap.html


2018-02-12 8:32 GMT+01:00 benoit74 <notifications@github.com>:

**Comment by benoit74** [comment]
Did you achieved your goal? Do you need more help?
(Otherwise I'll close the issue)

2018-02-13 14:09 GMT+01:00 jzy3d <notifications@github.com>:
