### ISSUE TITLE
how many points i should give properly to plot the graph

### ISSUE THREAD

**Issue by GIRISHBR07** [benoit74/nzy3d-api#8]
I tried to give the 4 points(3d points), but i'm getting run time error caused by genereate_ticks().

please help me out!

**Comment by benoit74** [comment]
Hello,
Could you provide a small code snippet (e.g. on https://gist.github.com/) to
help investigate your issue?
Thanks

2018-02-20 7:42 GMT+01:00 GIRISHBR07 <notifications@github.com>:

**Comment by benoit74** [comment]
Solution explained in #9
ScatterPlot where not supported previously.
